### ISSUE TITLE
Project status / offer to help

### ISSUE THREAD

**Issue by danepowell** [consolidation/self-update#24]
Hey @greg-1-anderson, tl;dr: would you consider either giving me commit access to this project to help with maintenance, merging #21 and #23 and cutting a new release, or marking this project as abandoned / archived?

I see you haven't been active here in over a year. I'm guessing that, like me, you have a lot of competing priorities. I and many others rely on this package and it needs some updates and a new release to fix a critical regression in HEAD, specifically #21 and #23.

I'm happy to help if you'd like, and I would only merge critical PRs, unless we come to some other agreement.

Alternatively, if you don't have time to maintain this project and don't want help, it would be best if you marked it as abandoned / archived and I'll start a fork.

Please let me know what you'd prefer. Thanks!

**Comment by greg-1-anderson** [comment]
I have given you admin access to this repo. Please feel free to release any PR you have confidence in. I haven't been merging PRs here because there are no tests, I haven't had time to write tests, and ad-hoc testing is time consuming. I trust your judgement vis-a-vis what constitutes confidence in a PR, though. Thank you for volunteering.
